### ISSUE TITLE
Triggering ll via airflow

### ISSUE THREAD

**Issue by sebastianwindeck** [combit/ll-samples#1]
Hi, 

I would like to trigger a list&label report via python airflow and create a PDF-file.
How could I set this up?

Best, 
You do a great job.

**Comment by jbartlau** [comment]
Not familiar with Phython Airflow, however there's a Phython sample provided in the setup - attaching the sources for the coming version 25: [MAINWND.TXT](https://github.com/combit/ll-samples/files/3712258/MAINWND.TXT)

The PDF export would work as described [here ](https://forum.combit.net/t/export-without-user-interaction-using-direct-api/5091). Does that help already?

**Comment by sebastianwindeck** [comment]
Yes, that helps a lot thank you.
